### ISSUE TITLE
Support for GeoIP2 / .mmdb files

### ISSUE THREAD

**Issue by drn05r** [eprints/irstats2#108]
RHEL 9 now longer provides GeoIP / perl-Geo-IP and only natively supports mmdblookup (rather than geoiplookup), .mmdb database files and GeoIP2.  We need to update EPrints/Plugin/Stats/Processor/Access/Country.pm to support GeoIP2.

**Comment by mpbraendle** [comment]
That is what we have:
`
package EPrints::Plugin::Stats::Processor::Access::Country;

our @ISA = qw/ EPrints::Plugin::Stats::Processor::Access /;

use strict;
use lib "/usr/local/eprints/perl_cpan/lib/perl5";

# Processor::Access::Country
#
# Processes the Country codes from Access records. Provides the 'eprint_countries' datatype
# Note that this requires Geo::IP or Geo::IP::PurePerl to work.
#
# From: http://search.cpan.org/~borisz/Geo-IP-PurePerl-1.25/lib/Geo/IP/PurePerl.pm#SEE_ALSO
# Geo::IP - this now has the PurePerl code merged it, so it supports both XS and Pure Perl
# implementations. The XS implementation is a wrapper around the GeoIP C API, which is much
# faster than the Pure Perl API.
# I think this has been in place since ~Aug 2008

sub new
{
        my( $class, %params ) = @_;

        my $self = $class->SUPER::new( %params );
        return $self if( !$self->{session} );

        # UZH CHANGE ZORA-777 2020/08/26/mb GeoIP2
        # if possible, use the GeoIP data file shipped with EPrints
        # my $dat_file = $self->{session}->config( "lib_path").'/geoip/GeoIP.dat';

        # alternatively use the global one
        # $dat_file = 1 if( !-e $dat_file );

        #Test Geo::IP first - it's faster!
        #foreach my $pkg ( 'Geo::IP', 'Geo::IP::PurePerl' )
        #{
        #       if( EPrints::Utils::require_if_exists( $pkg ) )
        #       {
        #               $self->{geoip} = $pkg->new( $dat_file );
        #               last if( defined $self->{geoip} );
        #       }
        #}

        if( EPrints::Utils::require_if_exists( 'GeoIP2::Database::Reader' ) )
        {
                $self->{geoip} = GeoIP2::Database::Reader->new(
                        file => '/usr/local/eprints/var/GeoLite2-Country.mmdb',
                        locales => [ 'en', 'de' ],
                );
        }
        # END UZH CHANGE ZORA-777

        if( !defined $self->{geoip} )
        {
                $self->{advertise} = 0;
                $self->{disable} = 1;
                $self->{error} = "Failed to load required module for Processor::Access::Country. Country information will not be available.";
                return $self;
        }

sub process_record
{
        my ($self, $record, $is_download) = @_;

        return unless( $is_download );

        my $ip = $record->{requester_id};
        return unless( defined $ip );

        # UZH CHANGE ZORA-777 2020/08/26/mb GeoIP2
        # my $code = $self->{geoip}->country_code_by_addr( $ip );
        my $code;
        eval
        {
                $code = $self->{geoip}->country( ip => $ip )->country()->iso_code();
        };
        # END UZH CHANGE ZORA-777

        if( defined $code && length $code )
        {
                my $epid = $record->{referent_id};
                return unless( defined $epid );

                my $date = $record->{datestamp}->{cache};
                $self->{cache}->{"$date"}->{$epid}->{$code}++;
        }
}


1;
`

**Comment by drn05r** [comment]
Thanks.  That looks much the same as the code I had already written except for I still want to allow the current libraries or people upgrading IRStats2 in situ would have to install OS packages as well.

The `eval` round the complex get country ISO code from IP line looks like a sensible addition.
