### ISSUE TITLE
Google Chrome browser statistics wrong

### ISSUE THREAD

**Issue by mpbraendle** [eprints/irstats2#66]
Due to a faulty match procedure in Browsers.pm, accesses by Google Chrome browser are (practically) not counted, but are attributed to Apple Safari (see http://www.eprints.org/tech.php/20781.html )

There are two possibilities to remedy this:
- either replace "Apple Safari" by "Safari" in line 20
- or change line 54 as follows:
  #       foreach( keys %$BROWSERS_SIGNATURES )
       foreach( sort keys %$BROWSERS_SIGNATURES )

The statistics must be recalculated from scratch.

**Comment by jesusbagpuss** [comment]
See also #87.  
The `sort` fix only works because 'Chrome' is alphabetically before Safari.

Might be worth looking at e.g. https://github.com/ua-parser/ for a more 'proper' solution?
Although I'm not sure whether this overhead is needed (it detects OS, Browser, versions - but thiese *could* be interesting when looking at stats too?
